# Generated by Django 2.1.7 on 2019-04-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190403_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
