# Generated by Django 2.1.7 on 2019-04-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_todomodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='title',
            field=models.CharField(default='Default Title', max_length=20, verbose_name='Title'),
        ),
    ]
